name: Test bash
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          sudo apt-get install php jq
      - name: Create bash config
        run: |
          touch ~/.bashrc
      - name: Install scratches
        run: |
          curl -sSL https://raw.githubusercontent.com/janoelze/scratches.sh/main/install.sh | bash
      - name: Tree of home directory
        run: |
          tree ~
      - name: Output bash config
        run: cat ~/.bashrc
      - name: Create mock scratch
        run: |
          mkdir -p ~/scratches/env
          mkdir -p ~/scratches/env/hello-world
          echo "Hello World!" > ~/scratches/env/hello-world/index.html
      - name: Create mock scratch
        run: |
          mkdir -p ~/scratches/env
          mkdir -p ~/scratches/env/hello-world
          echo "Hello World!" > ~/scratches/env/hello-world/index.html
      - name: List scratches
        run: |
          source ~/.bashrc
          scratches ls
      - name: Start scratch
        run: |
          source ~/.bashrc
          scratches start hello-world